version: 2.1

aliases:
  - &docker
    - image: cimg/node:14.17.0

jobs:
  setup:
    docker: *docker
    steps:
      - checkout
      - run:
          name: Add npmrc
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
            echo "scope=datacamp" >> .npmrc
            echo "@datacamp:registry=https://registry.npmjs.org/" >> .npmrc
            echo "scripts-prepend-node-path=true" >> .npmrc
      - restore_cache:
          name: Restore yarn cache
          keys:
            - cache-v6-{{ checksum "yarn.lock" }}
            - cache-v6-
      - run:
          name: Install packages
          command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
      - save_cache:
          name: Save cypress binary cache
          key: cypress-binary-v1-{{ checksum "yarn.lock" }}
          paths:
            - /root/.cache/Cypress
      - save_cache:
          name: Save cache
          key: cache-v6-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache
      - persist_to_workspace:
          root: '.'
          paths:
            - '*'
  build:
    docker: *docker
    steps:
      - attach_workspace:
          at: '.'
      - run:
          name: Build distribution
          command: yarn build
      - persist_to_workspace:
          root: '.'
          paths:
            - '*'
  test:
    docker:
      - image: cypress/base:14.17.0
    steps:
      - attach_workspace:
          at: '.'
      - run:
          name: Lint codebase
          command: yarn lint
      - run:
          name: Check code formatting
          command: yarn format:check
      - run:
          name: Lint commits
          command: yarn lint-commits
      - run:
          name: Run unit tests
          command: yarn test-unit:ci
      - restore_cache:
          name: Restore cypress binary cache
          keys:
            - cypress-binary-v1-{{ checksum "yarn.lock" }}
            - cypress-binary-v1-
      - run:
          name: Run stories and a11y audits
          command: yarn test-stories:ci
  release:
    docker: *docker
    steps:
      - attach_workspace:
          at: '.'
      - run:
          name: Add git credentials
          command: |
            git config --global user.email engineering+datacamp-circleci-user@datacamp.com
            git config --global user.name datacamp-circleci-user
      - run:
          name: Release npm package
          command: yarn release

workflows:
  version: 2
  build_test_release:
    jobs:
      - setup:
          context: org-global
      - build:
          requires:
            - setup
      - test:
          requires:
            - build
      - release:
          requires:
            - test
          context: org-global
          filters:
            branches:
              only:
                - master
