version: 2.1

jobs:
  build_and_test:
    docker:
      - image: cypress/base:14.17.0
    steps:
      - checkout
      - run:
          name: Add npmrc
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
            echo "scope=datacamp" >> .npmrc
            echo "@datacamp:registry=https://registry.npmjs.org/" >> .npmrc
            echo "scripts-prepend-node-path=true" >> .npmrc
      - restore_cache:
          name: Restore cache
          keys:
            - project-cache-v2-{{ checksum "yarn.lock" }}
      - run:
          name: Install packages
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save cache
          key: project-cache-v2-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache
      - run:
          name: Build distribution
          command: yarn build
      - persist_to_workspace:
          root: '.'
          paths:
            - '*'
      - run:
          name: Lint codebase
          command: yarn lint
      - run:
          name: Check code formatting
          command: yarn format:check
      - run:
          name: Lint commits
          command: yarn lint-commits
      - run:
          name: Run unit tests
          command: yarn test-unit:ci
      - run:
          name: Run e2e stories tests
          command: yarn test-stories:ci
  release:
    docker:
      - image: cimg/node:14.17.0
    steps:
      - checkout
      - attach_workspace:
          at: '.'
      - run:
          name: Add git credentials
          command: |
            git config --global user.email engineering+datacamp-circleci-user@datacamp.com
            git config --global user.name datacamp-circleci-user
      - run:
          name: Release npm package
          command: yarn release

workflows:
  version: 2
  build_test_release:
    jobs:
      - build_and_test:
          context: org-global
      - release:
          requires:
            - build_and_test
          context: org-global
          filters:
            branches:
              only:
                - master
