version: 2.1

aliases:
  - &docker
    - image: cimg/node:14.17.3

jobs:
  build:
    docker: *docker
    environment:
      GIT_SSH_COMMAND: 'ssh -i ~/.ssh/id_rsa -o IdentitiesOnly=yes'
    steps:
      - checkout
      - run:
          name: Add npmrc
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
            echo "scope=datacamp" >> .npmrc
            echo "@datacamp:registry=https://registry.npmjs.org/" >> .npmrc
            echo "scripts-prepend-node-path=true" >> .npmrc
      - run:
          name: Install packages
          command: yarn install
      - run:
          name: Build distribution
          command: yarn build
      - run:
          name: Lint codebase
          command: yarn lint
      - run:
          name: Check code formatting
          command: yarn format:check
      - run:
          name: Lint commits
          command: yarn lint:commits
      - run:
          name: Run unit tests
          command: yarn test:coverage
      - run:
          name: Release npm package
          command: yarn release

workflows:
  version: 2
  build_test_release:
    jobs:
      - build:
          context: org-global
